name: "Korber-Maven-Demo"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github-oidc-test'
      MAVEN_REPO: 'korber-workshop-maven-dev'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

      - name: Run JFrog CLI Ping
        run: jf rt ping

      - name: Configure Maven repositories in JFrog CLI
        run: |
          jf mvnc --repo-resolve-releases ${{ env.MAVEN_REPO }} \
                  --repo-resolve-snapshots ${{ env.MAVEN_REPO }} \
                  --repo-deploy-releases ${{ env.MAVEN_REPO }} \
                  --repo-deploy-snapshots ${{ env.MAVEN_REPO }}

      - name: JFrog Xray Audit command
        run: jf audit
        
      - name: Build and Install Maven Project
        run: jf mvn clean install -DskipTests --build-name="anilkt-mvn-publish" --build-number=${{ github.run_number }}

      - name: Collect Env
        run: jf rt bce korber-mvn-publish ${{ github.run_number }}

      - name: Collect VCS info
        run: jf rt bag korber-mvn-publish ${{ github.run_number }}

      - name: Publish build
        run: jf rt bp korber-mvn-publish ${{ github.run_number }}
